### ISSUE TITLE
Nordic special characters in the metadata

### ISSUE THREAD

**Issue by jnsjak** [Norconex/committer-idol#2]
We’re having a problem with special characters in the importer.

We use a ScriptTransformer to extract certain patterns from the content and insert the extracted values as metafields on the document to index. This works very well, however whenever these values contains special characters (we’re in Scandinavia so there’s a lot of those), they get converted to Java Literals (\uXXXX) in the output. So “smörgåsbord” becomes “sm\u00F6rg\u00E5sbord” in the .meta file, it is not changed in the parsed .cntnt however. 

In fact this happens if I just set a constant tagger like so:
<div>&lt;tagger class="com.norconex.importer.handler.tagger.impl.ConstantTagger"&gt;</div><div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &lt;constant name="SpecialChars"&gt;smörgåsbord&lt;/constant&gt;&lt;/tagger&gt;</div>

Which results in: 
SpecialChars = sm\u00F6rg\u00E5sbord
in the .meta file.

The content being fetched is UTF-8 and the response header is set to utf-8, sourceCharset is set to UTF-8, xml-configuration is UTF-8, -Dfile.encoding also to UTF8. How can we prevent the special chars from being represented in this java format?
Please let me know if you need more info to recreate, but basically it happens to me if I download the minimum configuration, point the URL to www.example.com, add the tagger above and use the filecommitter.

The content is ingested into an IDOL instance and that is not able to handle such encoding and thus the searches break and we need to find a way around it.

Thanks and hope you are able to help :)

**Comment by essiembre** [comment]
I think we have a fix.  Can you please try the latest snapshot version of the IDOL Committer and confirm?
https://norconex.com/collectors/committer-idol/download

**Comment by jnsjak** [comment]
Yes I can confirm, now I get UTF8 all the way through the process and into idol.
Thanks for the swift fix!

Kind regards
Jens.
